# Generated by Django 5.2.16 on 2026-07-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
